import swaggerAutogen from 'swagger-autogen';

const doc = {
  info: {
    title: 'My API',
    description: 'Swagger file auto generated by swagger-autogen'
  },
  host: 'localhost:3000'
};

const outputFile = './swagger-output.json';
const routes = ['./Backend/server.js'];

/* NOTE: If you are using the express Router, you must pass in the 'routes' only the 
root file where the route starts, such as index.js, app.js, routes.js, etc ... */

swaggerAutogen()(outputFile, routes, doc);